name: Build_CSCG.Abstract

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CSCG.Anstract/CSCG.Anstract.csproj
    - name: Build
      run: dotnet build CSCG.Anstract/CSCG.Anstract.csproj --no-restore
