name: Build CSCG.Abstract

on:
  push:
    paths: [ CSCG.Abstract/** ]
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]
    paths: [ CSCG.Abstract/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CSCG.Abstract/CSCG.Abstract.csproj
    - name: Build
      run: dotnet build CSCG.Abstract/CSCG.Abstract.csproj --no-restore
