name: CSCG.Abstract.CD

on:
  workflow_run:
    workflows: ["CSCG.Abstract.CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo hi
