name: CSCG.Roslyn.CI

on:
  push:
    paths: [ CSCG.Roslyn/**, .github/workflows/CSCG.Roslyn.CI.yml ]
    branches: [ main, feature/* ]
  pull_request:
    paths: [ CSCG.Roslyn/**, .github/workflows/CSCG.Roslyn.CI.yml ]
    branches: [ main, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CSCG.Roslyn/CSCG.Roslyn.csproj
    - name: Build
      run: dotnet build CSCG.Roslyn/CSCG.Roslyn.csproj --no-restore
