name: CSCG.Abstract.CD

on:
  workflow_run:
    workflows: ["CSCG.Abstract.CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore CSCG.Abstract/CSCG.Abstract.csproj
    - name: Build
      run: dotnet build CSCG.Abstract/CSCG.Abstract.csproj --configuration Release --no-restore
    - name: Pack
      run: dotnet pack CSCG.Abstract/CSCG.Abstract.csproj --configuration Release --no-build --no-restore --output .
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: CSCG.Abstract/CSCG.Abstract.csproj
          NUGET_KEY: ${{secrets.PUBLISH_TO_NUGET_ORG}}
          INCLUDE_SYMBOLS: true
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
