name: CSCG.Roslyn.CD

on:
  workflow_run:
    workflows: ["CSCG.Roslyn.CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CSCG.Roslyn/CSCG.Roslyn.csproj
    - name: Build
      run: dotnet build CSCG.Roslyn/CSCG.Roslyn.csproj --configuration Release --no-restore
    - name: Pack
      run: dotnet pack CSCG.Roslyn/CSCG.Roslyn.csproj -p:NuspecFile=CSCG.Roslyn.nuspec -p:NuspecProperties="version=0.2.1" --configuration Release --include-symbols --no-build --no-restore --output .
    - name: PushNuget
      run: dotnet nuget push *.nupkg --source Nuget.org --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
